status = error
appenders = console, file

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

appender.file.type = File
appender.file.name = file
appender.file.fileName = logs/automation.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

loggers = org_example, org_selenium, io_appium

logger.org_example.name = org.example
logger.org_example.level = debug
logger.org_example.additivity = false

logger.org_selenium.name = org.openqa.selenium
logger.org_selenium.level = info
logger.org_selenium.additivity = false

logger.io_appium.name = io.appium
logger.io_appium.level = info
logger.io_appium.additivity = false

rootLogger.level = info
rootLogger.appenderRefs = console, file
rootLogger.appenderRef.console.ref = console
rootLogger.appenderRef.file.ref = file
